CREATE TYPE "public"."ai_provider" AS ENUM('openai', 'azure_openai', 'ollama', 'copilot');--> statement-breakpoint
CREATE TYPE "public"."communication_type" AS ENUM('chat', 'email', 'meeting', 'personality');--> statement-breakpoint
CREATE TYPE "public"."proposal_outcome" AS ENUM('success', 'failure', 'pending');--> statement-breakpoint
CREATE TYPE "public"."proposal_status" AS ENUM('draft', 'in_review', 'submitted', 'won', 'lost');--> statement-breakpoint
CREATE TYPE "public"."stakeholder_role" AS ENUM('CTO', 'PO', 'FUNCTIONAL_TECH_LEAD', 'TECH_LEAD', 'OTHER');--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "persona_analizer_ts_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_ai_provider_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_ai_provider_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"companyId" integer,
	"provider" "ai_provider" NOT NULL,
	"modelName" varchar(255),
	"endpoint" varchar(500),
	"apiVersion" varchar(100),
	"options" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"industry" varchar(255),
	"businessIntent" text,
	"technologyIntent" text,
	"developmentStacks" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"certifications" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"standards" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"partnerships" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"referenceArchitectures" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"engineeringGuidelines" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_generated_communication" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_generated_communication_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposalId" integer NOT NULL,
	"personaId" integer,
	"stakeholderRole" "stakeholder_role" NOT NULL,
	"aiProvider" "ai_provider" NOT NULL,
	"promptContext" text,
	"generatedMessage" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_persona_communication" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_persona_communication_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"companyId" integer NOT NULL,
	"personaId" integer NOT NULL,
	"type" "communication_type" NOT NULL,
	"subject" varchar(255),
	"content" text NOT NULL,
	"occurredAt" timestamp with time zone,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_persona" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_persona_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"companyId" integer NOT NULL,
	"fullName" varchar(255) NOT NULL,
	"email" varchar(255),
	"jobDescription" text,
	"personalitySummary" text,
	"personalPreferences" text,
	"pastExperiences" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_evaluation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_evaluation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposalId" integer NOT NULL,
	"successSignals" text,
	"failureSignals" text,
	"successScore" integer DEFAULT 50 NOT NULL,
	"failureRiskScore" integer DEFAULT 50 NOT NULL,
	"recommendation" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_stakeholder" (
	"proposalId" integer NOT NULL,
	"personaId" integer NOT NULL,
	"role" "stakeholder_role" NOT NULL,
	"influenceLevel" integer DEFAULT 3 NOT NULL,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "persona_analizer_ts_proposal_stakeholder_proposalId_personaId_role_pk" PRIMARY KEY("proposalId","personaId","role")
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"companyId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"summary" text,
	"intentSignals" text,
	"technologyFit" text,
	"status" "proposal_status" DEFAULT 'draft' NOT NULL,
	"outcome" "proposal_outcome" DEFAULT 'pending' NOT NULL,
	"outcomeReason" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "persona_analizer_ts_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_account" ADD CONSTRAINT "persona_analizer_ts_account_userId_persona_analizer_ts_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."persona_analizer_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_ai_provider_config" ADD CONSTRAINT "persona_analizer_ts_ai_provider_config_companyId_persona_analizer_ts_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."persona_analizer_ts_company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_generated_communication" ADD CONSTRAINT "persona_analizer_ts_generated_communication_proposalId_persona_analizer_ts_proposal_id_fk" FOREIGN KEY ("proposalId") REFERENCES "public"."persona_analizer_ts_proposal"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_generated_communication" ADD CONSTRAINT "persona_analizer_ts_generated_communication_personaId_persona_analizer_ts_persona_id_fk" FOREIGN KEY ("personaId") REFERENCES "public"."persona_analizer_ts_persona"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_persona_communication" ADD CONSTRAINT "persona_analizer_ts_persona_communication_companyId_persona_analizer_ts_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."persona_analizer_ts_company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_persona_communication" ADD CONSTRAINT "persona_analizer_ts_persona_communication_personaId_persona_analizer_ts_persona_id_fk" FOREIGN KEY ("personaId") REFERENCES "public"."persona_analizer_ts_persona"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_persona" ADD CONSTRAINT "persona_analizer_ts_persona_companyId_persona_analizer_ts_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."persona_analizer_ts_company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_post" ADD CONSTRAINT "persona_analizer_ts_post_createdById_persona_analizer_ts_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."persona_analizer_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_evaluation" ADD CONSTRAINT "persona_analizer_ts_proposal_evaluation_proposalId_persona_analizer_ts_proposal_id_fk" FOREIGN KEY ("proposalId") REFERENCES "public"."persona_analizer_ts_proposal"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_stakeholder" ADD CONSTRAINT "persona_analizer_ts_proposal_stakeholder_proposalId_persona_analizer_ts_proposal_id_fk" FOREIGN KEY ("proposalId") REFERENCES "public"."persona_analizer_ts_proposal"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_stakeholder" ADD CONSTRAINT "persona_analizer_ts_proposal_stakeholder_personaId_persona_analizer_ts_persona_id_fk" FOREIGN KEY ("personaId") REFERENCES "public"."persona_analizer_ts_persona"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal" ADD CONSTRAINT "persona_analizer_ts_proposal_companyId_persona_analizer_ts_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."persona_analizer_ts_company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_session" ADD CONSTRAINT "persona_analizer_ts_session_userId_persona_analizer_ts_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."persona_analizer_ts_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "persona_analizer_ts_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "ai_provider_company_idx" ON "persona_analizer_ts_ai_provider_config" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "ai_provider_provider_idx" ON "persona_analizer_ts_ai_provider_config" USING btree ("provider");--> statement-breakpoint
CREATE UNIQUE INDEX "company_name_unique_idx" ON "persona_analizer_ts_company" USING btree ("name");--> statement-breakpoint
CREATE INDEX "company_industry_idx" ON "persona_analizer_ts_company" USING btree ("industry");--> statement-breakpoint
CREATE INDEX "generated_communication_proposal_idx" ON "persona_analizer_ts_generated_communication" USING btree ("proposalId");--> statement-breakpoint
CREATE INDEX "generated_communication_persona_idx" ON "persona_analizer_ts_generated_communication" USING btree ("personaId");--> statement-breakpoint
CREATE INDEX "persona_communication_persona_idx" ON "persona_analizer_ts_persona_communication" USING btree ("personaId");--> statement-breakpoint
CREATE INDEX "persona_communication_company_idx" ON "persona_analizer_ts_persona_communication" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "persona_communication_type_idx" ON "persona_analizer_ts_persona_communication" USING btree ("type");--> statement-breakpoint
CREATE INDEX "persona_company_idx" ON "persona_analizer_ts_persona" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "persona_email_idx" ON "persona_analizer_ts_persona" USING btree ("email");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "persona_analizer_ts_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "persona_analizer_ts_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "proposal_evaluation_proposal_idx" ON "persona_analizer_ts_proposal_evaluation" USING btree ("proposalId");--> statement-breakpoint
CREATE INDEX "proposal_stakeholder_proposal_idx" ON "persona_analizer_ts_proposal_stakeholder" USING btree ("proposalId");--> statement-breakpoint
CREATE INDEX "proposal_stakeholder_persona_idx" ON "persona_analizer_ts_proposal_stakeholder" USING btree ("personaId");--> statement-breakpoint
CREATE INDEX "proposal_company_idx" ON "persona_analizer_ts_proposal" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "proposal_status_idx" ON "persona_analizer_ts_proposal" USING btree ("status");--> statement-breakpoint
CREATE INDEX "proposal_outcome_idx" ON "persona_analizer_ts_proposal" USING btree ("outcome");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "persona_analizer_ts_session" USING btree ("userId");