CREATE TYPE "public"."chat_message_role" AS ENUM('user', 'assistant');
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_chat_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_chat_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposalId" integer NOT NULL,
	"defaultContext" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_chat_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_chat_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"role" "chat_message_role" NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_chat_session" ADD CONSTRAINT "persona_analizer_ts_proposal_chat_session_proposalId_persona_analizer_ts_proposal_id_fk" FOREIGN KEY ("proposalId") REFERENCES "public"."persona_analizer_ts_proposal"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_chat_message" ADD CONSTRAINT "persona_analizer_ts_proposal_chat_message_sessionId_persona_analizer_ts_proposal_chat_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."persona_analizer_ts_proposal_chat_session"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "proposal_chat_session_proposal_unique_idx" ON "persona_analizer_ts_proposal_chat_session" USING btree ("proposalId");
--> statement-breakpoint
CREATE INDEX "proposal_chat_session_proposal_idx" ON "persona_analizer_ts_proposal_chat_session" USING btree ("proposalId");
--> statement-breakpoint
CREATE INDEX "proposal_chat_message_session_idx" ON "persona_analizer_ts_proposal_chat_message" USING btree ("sessionId");
--> statement-breakpoint
CREATE INDEX "proposal_chat_message_role_idx" ON "persona_analizer_ts_proposal_chat_message" USING btree ("role");
