CREATE TABLE "persona_analizer_ts_proposal_meeting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_meeting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposalId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"audioUrl" varchar(500),
	"assemblyAiTranscriptId" varchar(255),
	"transcriptJson" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"summary" text,
	"summaryGeneratedAt" timestamp with time zone,
	"nextSteps" text,
	"nextStepsGeneratedAt" timestamp with time zone,
	"recordingDate" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_meeting_speaker" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_meeting_speaker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"meetingId" integer NOT NULL,
	"speakerId" integer NOT NULL,
	"speakerLabel" varchar(50) NOT NULL,
	"speakerName" varchar(255),
	"linkedStakeholderId" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "persona_analizer_ts_proposal_meeting_transcript" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persona_analizer_ts_proposal_meeting_transcript_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"meetingId" integer NOT NULL,
	"speakerId" integer NOT NULL,
	"speakerLabel" varchar(50) NOT NULL,
	"text" text NOT NULL,
	"confidence" real,
	"startTime" real,
	"endTime" real,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_meeting_speaker" ADD CONSTRAINT "persona_analizer_ts_proposal_meeting_speaker_meetingId_persona_analizer_ts_proposal_meeting_id_fk" FOREIGN KEY ("meetingId") REFERENCES "public"."persona_analizer_ts_proposal_meeting"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_meeting_speaker" ADD CONSTRAINT "persona_analizer_ts_proposal_meeting_speaker_linkedStakeholderId_persona_analizer_ts_persona_id_fk" FOREIGN KEY ("linkedStakeholderId") REFERENCES "public"."persona_analizer_ts_persona"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_meeting_transcript" ADD CONSTRAINT "persona_analizer_ts_proposal_meeting_transcript_meetingId_persona_analizer_ts_proposal_meeting_id_fk" FOREIGN KEY ("meetingId") REFERENCES "public"."persona_analizer_ts_proposal_meeting"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "persona_analizer_ts_proposal_meeting" ADD CONSTRAINT "persona_analizer_ts_proposal_meeting_proposalId_persona_analizer_ts_proposal_id_fk" FOREIGN KEY ("proposalId") REFERENCES "public"."persona_analizer_ts_proposal"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "proposal_meeting_speaker_meeting_idx" ON "persona_analizer_ts_proposal_meeting_speaker" USING btree ("meetingId");
--> statement-breakpoint
CREATE INDEX "proposal_meeting_speaker_stakeholder_idx" ON "persona_analizer_ts_proposal_meeting_speaker" USING btree ("linkedStakeholderId");
--> statement-breakpoint
CREATE UNIQUE INDEX "proposal_meeting_speaker_unique_idx" ON "persona_analizer_ts_proposal_meeting_speaker" USING btree ("meetingId","speakerId");
--> statement-breakpoint
CREATE INDEX "proposal_meeting_transcript_meeting_idx" ON "persona_analizer_ts_proposal_meeting_transcript" USING btree ("meetingId");
--> statement-breakpoint
CREATE INDEX "proposal_meeting_transcript_speaker_idx" ON "persona_analizer_ts_proposal_meeting_transcript" USING btree ("speakerId");
--> statement-breakpoint
CREATE INDEX "proposal_meeting_proposal_idx" ON "persona_analizer_ts_proposal_meeting" USING btree ("proposalId");
--> statement-breakpoint
CREATE INDEX "proposal_meeting_assembly_ai_idx" ON "persona_analizer_ts_proposal_meeting" USING btree ("assemblyAiTranscriptId");