CREATE TABLE IF NOT EXISTS persona_analizer_ts_ai_prompt_version (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prompt_id integer NOT NULL REFERENCES persona_analizer_ts_ai_prompt(id) ON DELETE CASCADE,
  version integer NOT NULL,
  prompt_template text NOT NULL,
  system_instruction text,
  change_notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ai_prompt_version_prompt_version_unique_idx
  ON persona_analizer_ts_ai_prompt_version(prompt_id, version);

CREATE INDEX IF NOT EXISTS ai_prompt_version_prompt_idx
  ON persona_analizer_ts_ai_prompt_version(prompt_id);

CREATE TABLE IF NOT EXISTS persona_analizer_ts_cache_metric (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service varchar(100) NOT NULL,
  input_hash varchar(64) NOT NULL,
  hit_count integer NOT NULL DEFAULT 0,
  miss_count integer NOT NULL DEFAULT 0,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS cache_metric_service_hash_unique_idx
  ON persona_analizer_ts_cache_metric(service, input_hash);

CREATE INDEX IF NOT EXISTS cache_metric_service_idx
  ON persona_analizer_ts_cache_metric(service);

CREATE TABLE IF NOT EXISTS persona_analizer_ts_api_metric (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service varchar(100) NOT NULL,
  input_tokens integer,
  output_tokens integer,
  total_cost numeric(10, 6),
  processing_time_ms integer,
  was_cache boolean NOT NULL DEFAULT false,
  had_error boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS api_metric_service_idx
  ON persona_analizer_ts_api_metric(service);

CREATE INDEX IF NOT EXISTS api_metric_created_idx
  ON persona_analizer_ts_api_metric(created_at);
